#!/bin/sh
## Debian check tool to see if apt-get upgrade is needed or not
## (c) 2017 by Ahmed Ismail <aismail@auto.tuwien.ac.at>
## v0.01

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo "Simple script to check the Debian Distribution Version and Release"
else
	UNAME=/bin/uname
	LSBRELEASE=/usr/bin/lsb_release
	UNAME_OUTPUT=$( $UNAME -a )
	LSBRELEASE_OUTPUT=$( $LSBRELEASE -d | awk '{$1=""; print $0}' )
        RELEASE_VERSION=$( echo "$LSBRELEASE_OUTPUT" | awk '{print $3}' )
        if [ $(echo "$LSBRELEASE_OUTPUT" | awk '{print $1}'| grep Debian | wc -w | bc -l) -eq 1 ]; then
            # https://wiki.debian.org/DebianReleases
            RELEASE_STABLE=8.9 # Stretch
            RELEASE_LTS=8.8 # Jessie LTS expires ~June 6th 2020
#           RELEASE_LTS=8.8 # Wheezy LTS expires 2018-05-31
        fi
        if [ $(echo "$LSBRELEASE_OUTPUT" | awk '{print $1}'| grep Ubuntu | wc -w | bc -l) -eq 1 ]; then
            # https://wiki.ubuntu.com/Releases
            RELEASE_STABLE=16.04.3 # Xenial Xerus - LTS - Released Aug 3rd 2017
            RELEASE_LTS=14.04.5 # Xenial Xerus - LTS - End of Life April 2019
        fi
        CMP_RESULT_STABLE=$( echo "$RELEASE_VERSION < $RELEASE_STABLE" | bc -l)
        CMP_RESULT_LTS=$( echo "$RELEASE_VERSION < $RELEASE_LTS" | bc -l)
        if [ "$CMP_RESULT_STABLE" -eq 1 ]; then
            echo "RELEASE CRITICAL: Outdated distribution release - $LSBRELEASE_OUTPUT $UNAME_OUTPUT"
            exit 2
        elif [ "$CMP_RESULT_LTS" -eq 1 ]; then
            echo "RELEASE WARN: Outdated distribution release (LTS) - $LSBRELEASE_OUTPUT $UNAME_OUTPUT"
            exit 1
        else
            echo "RELEASE OK: $LSBRELEASE_OUTPUT $UNAME_OUTPUT"
            exit 0
        fi
fi
